steps:
name: 'gcr.io/cloud-builders/docker'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull container from dockerhub'
    args: ['pull', 'onsdigital/cir:${BRANCH_NAME}']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Tag the container with SHA'
    args: ['tag', 'onsdigital/cir:${BRANCH_NAME}', 'gcr.io/${PROJECT_ID}/cir/cir:${SHORT_SHA}']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push SHA tagged container to GCR'
    args: ['push', 'gcr.io/${PROJECT_ID}/cir/cir:${SHORT_SHA}']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy the container to cloudrun'
    args: [ 'run', 'deploy', 'cir', '--image', 'gcr.io/${PROJECT_ID}/cir/cir:${SHORT_SHA}',
            '--region', $LOCATION, '--allow-unauthenticated', '--ingress', 'internal-and-cloud-load-balancing' ]
options:
  logging: CLOUD_LOGGING_ONLY
