steps:
  - name: docker
    id: "Build and push docker image"
    entrypoint: sh
    args:
      - "-c"
      - |
        docker build -t "europe-west2-docker.pkg.dev/ons-sds-dns/cir/${PROJECT_ID}:latest" -t "europe-west2-docker.pkg.dev/ons-sds-dns/cir/${PROJECT_ID}:${TAG_NAME}" .
        docker push "europe-west2-docker.pkg.dev/ons-sds-dns/cir/${PROJECT_ID}:latest"
        docker push "europe-west2-docker.pkg.dev/ons-sds-dns/cir/${PROJECT_ID}:${TAG_NAME}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy docker image to cloud run"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "cir",
        "--image",
        "europe-west2-docker.pkg.dev/ons-sds-dns/cir/${PROJECT_ID}:latest",
        "--region",
        "europe-west2",
        "--allow-unauthenticated",
        "--ingress",
        "internal-and-cloud-load-balancing",
        "--update-env-vars",
        "CIR_APPLICATION_VERSION=${TAG_NAME}",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Google Artifact Registry
images:
  - europe-west2-docker.pkg.dev/ons-sds-dns/cir/${PROJECT_ID}:${TAG_NAME}
  - europe-west2-docker.pkg.dev/ons-sds-dns/cir/${PROJECT_ID}:latest
