version: "3.2"
services:
  storage:
    image: oittaa/gcp-storage-emulator
    environment:
      - PORT=9026
    ports:
      - 9026:9026
    volumes:
      - ./devtools/gcp-storage-emulator/data:/storage
    container_name: storage-cir
  firestore:
    image: spine3/firebase-emulator
    ports:
      - 8200:8200
      - 5050:5050
      - 8086:8086
    environment:
      - GCP_PROJECT=emulated-project-id
      - ENABLE_UI=true
    volumes:
      - ./devtools/firebase-emulator:/firebase
      - ./devtools/firebase-emulator:/firebase/baseline-data
    container_name: firestore-cir
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    environment:
      - CONF=local-docker
      - PROJECT_ID=emulated-project-id
      - CI_STORAGE_BUCKET_NAME=emulated-ci-bucket
      - PUBLISH_CI_TOPIC_ID=emulated-cir-topic
      - LOG_LEVEL=DEBUG
      - PORT=3030
      - PUBSUB_EMULATOR_HOST=firestore:8086
      - PUBSUB_PROJECT_ID=emulated-project-id
      - FIRESTORE_EMULATOR_HOST=firestore:8200
      - FIRESTORE_PROJECT_ID=emulated-project-id
      - SERVICE_ACCOUNT_JSON_FILE=test
      - STORAGE_EMULATOR_HOST=http://storage:9026
    volumes:
      - ./app:/code/app
      - ./devtools:/devtools
    restart: on-failure
    depends_on:
      - firestore
      - storage
    container_name: api-cir