name: push-to-main
run-name: Push latest app to dockerhub
on:
  push:
    branches:
      - main
jobs:
  push-latest-app-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build -t onsdigital/cir:latest .
      - name: Push built container to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag [latest]"
          docker push onsdigital/cir:latest
