name: release
run-name: Push published app to dockerhub
on:
  release:
    branches:
      - main
    types: [published]
jobs:
  push-published-app-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build -t onsdigital/cir:${{github.ref_name}} .
      - name: Push built container to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag ${{github.ref_name}}"
          docker push onsdigital/cir:${{github.ref_name}}
